<template>
  <div id="content">
    <h2 class="content-title">Manage Category</h2>
    <div class="box-table">
      <div class="box-table-head">Header table</div>
      <div class="box-table-body">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>name</th>
              <th>description</th>
              <th>CreateAt</th>
              <th>UpdateAt</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>News</td>
              <td>Tin tức</td>
              <td>04/04/2023</td>
              <td>04/04/2023</td>
              <td>
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="edit"
                />
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="trash"
                />
              </td>
            </tr>
            <tr>
              <td>1</td>
              <td>News</td>
              <td>Tin tức</td>
              <td>04/04/2023</td>
              <td>04/04/2023</td>
              <td>
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="edit"
                />
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="trash"
                />
              </td>
            </tr>
            <tr>
              <td>1</td>
              <td>News</td>
              <td>Tin tức</td>
              <td>04/04/2023</td>
              <td>04/04/2023</td>
              <td>
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="edit"
                />
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="trash"
                />
              </td>
            </tr>
            <tr>
              <td>1</td>
              <td>News</td>
              <td>Tin tức</td>
              <td>04/04/2023</td>
              <td>04/04/2023</td>
              <td>
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="edit"
                />
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="trash"
                />
              </td>
            </tr>
            <tr>
              <td>1</td>
              <td>News</td>
              <td>Tin tức</td>
              <td>04/04/2023</td>
              <td>04/04/2023</td>
              <td>
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="edit"
                />
                <box-icon
                  class="icon-action"
                  color="#867070"
                  size="18px"
                  animation="tada-hover"
                  name="trash"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>